# base_config.yaml
simulation_name: "Pinball"
tolerances:
  rom: 1.e-15
max_basis:
  rom: 20
snapshots:
  training: 10
  testing: 10
mesh:
  file: "data2/mesh.xdmf"
  function_file: "data2/mf.xdmf"
initial_conditions:
  velocity_file: "velocity_checkpoint.xdmf"
parameters:
  Re_range: [55,100]
  lifting_mu: 0.017
  online_Re: 80
bifurcation:
  enabled: false
  Re_start: 55.
  Re_end: 85.
  Re_num: 100.
  output_dir: "bifurcation_results"
analysis:
  error_analysis: false    # New parameter
  speedup_analysis: false  # New parameter