# base_config.yaml
simulation_name: "Pinball_rotation_picard_300"
tolerances:
  rom: 0.
max_basis:
  rom: 20
snapshots:
  training: 300
  testing: 100
mesh:
  file: "data2/mesh.xdmf"
  function_file: "data2/mf.xdmf"
initial_conditions:
  velocity_file: "velocity_checkpoint.xdmf"
parameters:
  Re_range: [55,100]
  lifting_mu: 0.017
  online_Re: 100
bifurcation:
  enabled: false
  Re_start: 55.
  Re_end: 85.
  Re_num: 100.
  output_dir: "bifurcation_results"
analysis:
  error_analysis: false   
  speedup_analysis: false  
